main: moe.rafal.shopgui.extension.treasury.ExtensionBukkitPlugin
name: shopgui-treasury-extension
version: ${project.version}
authors: [shitzuu <hello@rafal.moe>]
api-version: 1.20
depend: [Treasury, ShopGUIPlus]